services:
  ownercrud:
    image: ownercrud
    ports:
      - "18080:8080"
  petcrud:
    image: petcrud
    ports:
      - "18083:8080"
  auth:
    image: auth
    ports:
      - "18082:8080"
  orchestrate:
    image: orchestrate
    depends_on:
      - "ownercrud"
      - "petcrud"
      - "auth"
    ports:
      - "28080:8080"
